eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9999
spring:
  application:
    name: micro-weather-report-zuul-server
zuul:
  routes:
    api-a:
      path: /city/** #天气预报城市数据微服务
      serviceId: micro-weather-report-city
    api-b:
      path: /data/** #天气预报数据收集微服务
      serviceId: micro-weather-report-data-collection