eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000

server:
  port: 8081

spring:
  application:
    name: micro-weather-report-data-collection
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 0